<?php
/** @var $viewModel \Andrey\ServiceContract\ViewModel\ServiceContract */

$viewModel = $block->getViewModel();

$results =  $viewModel->scRepository();

    echo "<ul>";
    foreach ($results->getItems() as $result) {
        echo "<li>" . "Id: " . $result->getId() . "</li>";
        echo "<li>" . "Name: " . $result->getName() . "</li>";
        echo "<li>" . "Is Active: " . $result->getIsActive() . "</li>";
        echo "<li>" . "Created At: " . $result->getCreatedAt() . "</li>";
        echo "<li>" . "Update At: " . $result->getUpdatedAt() . "</li>";
        echo "<li>" . "Description: " . $result->getDescription() . "</li>";
    }
    echo "</ul>";
    echo "<br>"

?>


