<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Backend\Block\Template;
use DecimaDigital\MiddleUi\ViewModel\Data\CustomData;

/** @var Template $block */
/** @var CustomData $viewModel */
$viewModel = $block->getData('view_model');
?>
<section class="admin__page-section">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item">
            <div class="admin__page-section-item-content">
                <h4 style="width: 75%;background:#6f8992;padding: 10px 0;margin-bottom: 0;">
                    <span style="padding-left: 10px;color: #fff;">Included Information</span>
                </h4>
                <table style="width:75%;" class="admin__table-secondary subscription-account-information-table">
                    <?php if ($viewModel->getData()) : ?>
                        <tr>
                            <th><?= $block->escapeHtml(__('Name')); ?></th>
                            <td>
                                <span>
                                    <?= $block->escapeHtml(__($viewModel->getData()->getName())) ?>
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Description')); ?></th>
                            <td>
                                <span>
                                    <?= $block->escapeHtml(__($viewModel->getData()->getDescription())) ?>
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Created At')); ?></th>
                            <td>
                                <span>
                                    <?= $block->escapeHtml($viewModel->getData()->getCreatedAt()); ?>
                                </span>
                            </td>
                        </tr>

                    <?php else : ?>
                        <tr>
                            <td><?= $block->escapeHtml(__('Included Information not found.')); ?></td>
                        </tr>
                    <?php endif;?>
                </table>
            </div>
        </div>
    </div>
</section>
